# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-logger"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pjotr Prins"]
  s.date = "2012-02-27"
  s.description = "Log4r wrapper for BioRuby"
  s.email = "pjotr.public01@thebird.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-logger.gemspec",
    "lib/bio-logger.rb",
    "lib/bio/log/logger.rb",
    "lib/bio/log/loggercli.rb",
    "lib/bio/log/loggerfilter.rb",
    "lib/bio/log/loggersublevels.rb",
    "lib/bio/log/loggerusers.rb",
    "lib/bio/log/patchlog4r.rb",
    "spec/biologger_cli_spec.rb",
    "spec/biologger_spec.rb",
    "test/helper.rb",
    "test/test_bio-logger.rb"
  ]
  s.homepage = "https://github.com/pjotrp/bioruby-logger-plugin"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Log4r wrapper with extra features for roles and sane error handling"
  s.test_files = [
    "spec/biologger_cli_spec.rb",
    "spec/biologger_spec.rb",
    "test/helper.rb",
    "test/test_bio-logger.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
    else
      s.add_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<log4r>, [">= 1.1.9"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
  end
end

